###############################################################################
# This action will build the specified project and then run all unit tests.
###############################################################################
name: Build.Net.Scheduling

defaults:
  run:
    ############################################################
    # Set the root folder path where the solution is situated
    ############################################################
    working-directory: Nep.Scheduling

on:
  push:
    branches: [ main ]
    ####################################################################################
    # Trigger the push action if any file in the commit refers to the specified folder.
    ####################################################################################
    paths: 
      - '**/Nep.Scheduling/**'
  pull_request:
    branches: [ main ]
    ####################################################################################
    # Trigger the pull action if any file in the commit refers to the specified folder.
    ####################################################################################
    paths: 
      - '**/Nep.Scheduling/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET runtime emvironment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore packages and other dependencies
      run: dotnet restore Nep.Scheduling/Nep.Scheduling.csproj
    - name: Build the project
      run: dotnet build --no-restore Nep.Scheduling
    - name: Build and run the unit tests
      run: dotnet test --verbosity minimal Nep.Scheduling.Tests/Nep.Scheduling.Tests.csproj