###############################################################################
# This action will build the specified project and then run all unit tests.
###############################################################################
name: Build.Net.Scheduling

env:
    solution-folder: Nep.Scheduling

defaults:
  run:
    working-directory: ${{ solution-folder }}

on:
  push:
    branches: [ main ]
    paths: 
      - '**/Nep.Scheduling/**'
  pull_request:
    branches: [ main ]
    paths: 
      - '**/Nep.Scheduling/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore Nep.Scheduling/Nep.Scheduling.csproj
    - name: Build
      run: dotnet build --no-restore Nep.Scheduling
    - name: Test
      run: dotnet test --verbosity minimal Nep.Scheduling.Tests/Nep.Scheduling.Tests.csproj
      #run: dotnet test --no-build --verbosity minimal